Active: None
ActiveDSet: 0
Colors:
  0: '#2d2d2d'
  1: '#439084'
  2: '#ad6659'
  3: '#c0a15a'
  4: '#80b1d3'
  5: '#fdb462'
  6: '#b64e5d'
  7: '#434864'
Columns: 4
DSetDefaults:
  alpha: 1
  color: -1
  loc: None
  range: None
Datasets: 1
FigDefaults:
  Update: true
  height: None
  title: ''
  type: shade
  width: None
  xlabel: ''
  ylabel: ''
Figures: {}
FilesToLoad: IGNORE
Resize: true
Rows: 2
Update: true
dpi: 300
figsize:
  height: 4
  width: 7
fontsize:
  fontsize: 6
  ticksize: 3
  titlesize: 8
GridRatio: (1.449,.9)
Title: ''
TitleHeight: 0.4
gridspec_kw:
  bottom: 0.1
  hspace: 0.3
  left: 0.1
  right: 0.9
  top: 0.9
  wspace: 0.3
keyTree: {}
subplot_kw:
  sharex: true
  sharey: true
