Active: None
ActiveDSet: 0
Colors:
  0: '#2d2d2d'
  1: '#439084'
  2: '#ad6659'
  3: '#c0a15a'
  4: '#80b1d3'
  5: '#fdb462'
  6: '#b64e5d'
  7: '#434864'
Columns: 4
DSetDefaults:
  alpha: 1
  color: -1
  loc: None
  range: None
  label: None
  index: None
Datasets: 1
FigDefaults:
  Update: true
  height: None
  title: ''
  type: src.shade
  width: None
  xlabel: ''
  ylabel: ''
  yscale: ''
  xscale: ''
  xlim: ''
  ylim: ''
  xticks: ''
  xticklabels: ''
  yticks: ''
  yticklabels: ''
  x_major_tick_params:
    axis: 'x'
    which: 'major'
    direction: ''
    length: ''
    width: ''
    color: ''
    labelbottom: ''
    labeltop: ''
    labelleft: ''
    labelright: ''
    rotation: ''
    bottom: ''
    top: ''
    left: ''
    right: ''
  x_minor_tick_params:
    axis: 'x'
    which: 'minor'
    direction: ''
    length: ''
    width: ''
    color: ''
    labelbottom: ''
    labeltop: ''
    labelleft: ''
    labelright: ''
    rotation: ''
    bottom: ''
    top: ''
    left: ''
    right: ''
  y_major_tick_params:
    axis: 'y'
    which: 'major'
    direction: ''
    length: ''
    width: ''
    color: ''
    labelbottom: ''
    labeltop: ''
    labelleft: ''
    labelright: ''
    rotation: ''
    bottom: ''
    top: ''
    left: ''
    right: ''
  y_minor_tick_params:
    axis: 'y'
    which: 'minor'
    direction: ''
    length: ''
    width: ''
    color: ''
    labelbottom: ''
    labeltop: ''
    labelleft: ''
    labelright: ''
    rotation: ''
    bottom: ''
    top: ''
    left: ''
    right: ''
Figures: {}
FilesToLoad: "[]"
Resize: true
Rows: 2
Update: true
dpi: 300
FigureSize:
  height: 4
  width: 7
Fonts:
  Default:
    family: 'Alte Haas Grotesk'
    weight: 'roman'
    size: 4
  Title:
    family: ''
    weight: 'bold'
    size: 8
  Ticks:
    family: ''
    weight: ''
    size: 4
  Labels:
    family: ''
    weight: 'bold'
    size: 4
  Legend:
    family: ''
    weight: 'bold'
    size: 6
PlotSize: (1.294,.8)
Title:
  label: ''
  height: 0.25
Legend:
  ncol: 'Auto'
  loc: 'lower center'
gridspec_kw:
  bottom: 0.1
  hspace: 0.3
  left: 0.1
  right: 0.9
  top: 0.9
  wspace: 0.3
keyTree: {}
subplot_kw:
  sharex: true
  sharey: true
hidden_keys: ['keyTree', 'Active', 'ActiveDSet', 'Update', 'keyOrder', 'Resize', 'hidden_keys']
keyOrder: ['FilesToLoad', 'Colors', 'Columns', 'Rows', 'Datasets', 'FigureSize', 'dpi', 'gridspec_kw', 'PlotSize', 'Fonts', 'Title', 'Legend', 'subplot_kw', 'FigDefaults', 'DSetDefaults', 'Figures', 'keyTree', 'Active', 'ActiveDSet', 'Update', 'keyOrder', 'Resize', 'hidden_keys']
